version: '3.8'
services:
  postgres-db:
    container_name: postgres-db-ZooManager
    image: postgres:bullseye
    env_file: ./.env
    restart: always
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    deploy:
      mode: global
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
  zoo-manager:
    #build: https://github.com/Garin1998/ZooManager.git
    build: .
    image: zoo-manager:latest
    env_file: ./.env
    depends_on:
      - postgres-db
    ports:
      - ${ZOO_MANAGER_LOCAL_PORT}:${ZOO_MANAGER_DOCKER_PORT}
    volumes:
      - .m2:/root/.m2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_DOCKER_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      EXPIRATION_KEY: ${EXPIRATION_KEY}

