version: '3.8'
services:
  postgres-db:
    container_name: postgres-db-ZooManager
    image: postgres:bullseye
    restart: always
    ports:
      - "5432:5432"
    deploy:
      mode: global
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zoo_manager
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
  zoo-manager:
    build: .
    image: zoo-manager:latest
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: zoo_manager
      POSTGRES_HOST: postgres-db-ZooManager
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
