spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/zoo_manager
    username: admin
    password: password
security:
  jwt:
    secret-key: 90d2575217ed1e2422a563b193027d55ad98a1407def3067f71c1a8e54858f81
    expiration: 86400000 # a day
server:
  port: 8081